name: Automatic Rebase

on: issue_comment

jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      if: github.event.issue.pull_request != null && github.event.action == 'created' && github.event.comment.body == '/rebase'
    - name: Rebase
      uses: docker://cirrusactions/rebase:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
