on: issue_comment

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - if: github.event.body == '/rebase'
      uses: docker://cirrusactions/rebase:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
